"""add clients tasks timesheets timer_pause_resume

Revision ID: 354492b1a5cb
Revises: 001
Create Date: 2026-03-16 00:27:15.327147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '354492b1a5cb'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timesheets',
    sa.Column('week_start', sa.DateTime(), nullable=False),
    sa.Column('week_end', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', name='timesheetstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timesheets_id'), 'timesheets', ['id'], unique=False)
    op.drop_table('time_entry_tags')
    op.drop_table('project_tags')
    op.drop_table('task_tags')
    op.drop_table('project_assignments')
    op.drop_index(op.f('idx_tag_name_org'), table_name='tags')
    op.drop_index(op.f('idx_tag_org_active'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.add_column('clients', sa.Column('address', sa.Text(), nullable=True))
    op.alter_column('clients', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=254),
               existing_nullable=True)
    op.alter_column('clients', 'website',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index(op.f('idx_client_email'), table_name='clients')
    op.drop_index(op.f('idx_client_name_org'), table_name='clients')
    op.drop_index(op.f('idx_client_org_active'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_constraint(op.f('uq_client_name_org'), 'clients', type_='unique')
    op.drop_column('clients', 'currency')
    op.drop_column('clients', 'country')
    op.drop_column('clients', 'company_registration')
    op.drop_column('clients', 'tax_id')
    op.drop_column('clients', 'address_line2')
    op.drop_column('clients', 'postal_code')
    op.drop_column('clients', 'state')
    op.drop_column('clients', 'hourly_rate')
    op.drop_column('clients', 'address_line1')
    op.drop_column('clients', 'city')
    op.drop_column('clients', 'payment_terms')
    op.drop_index(op.f('idx_org_name'), table_name='organizations')
    op.drop_index(op.f('idx_org_slug_active'), table_name='organizations')
    op.drop_index(op.f('idx_project_client'), table_name='projects')
    op.drop_index(op.f('idx_project_name_org'), table_name='projects')
    op.drop_index(op.f('idx_project_org_active'), table_name='projects')
    op.drop_constraint(op.f('uq_project_name_org'), 'projects', type_='unique')
    op.drop_index(op.f('idx_task_assignee_status'), table_name='tasks')
    op.drop_index(op.f('idx_task_billable'), table_name='tasks')
    op.drop_index(op.f('idx_task_priority'), table_name='tasks')
    op.drop_index(op.f('idx_task_project_status'), table_name='tasks')
    op.drop_index(op.f('idx_time_entry_billable'), table_name='time_entries')
    op.drop_index(op.f('idx_time_entry_date_range'), table_name='time_entries')
    op.drop_index(op.f('idx_time_entry_project_date'), table_name='time_entries')
    op.drop_index(op.f('idx_time_entry_task'), table_name='time_entries')
    op.drop_index(op.f('idx_time_entry_user_date'), table_name='time_entries')
    op.add_column('timers', sa.Column('is_paused', sa.Boolean(), nullable=True))
    op.add_column('timers', sa.Column('paused_at', sa.DateTime(), nullable=True))
    op.add_column('timers', sa.Column('paused_duration', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_timer_project_running'), table_name='timers')
    op.drop_index(op.f('idx_timer_start_time'), table_name='timers')
    op.drop_index(op.f('idx_timer_task'), table_name='timers')
    op.drop_index(op.f('idx_timer_user_running'), table_name='timers')
    op.drop_index(op.f('idx_user_name_search'), table_name='users')
    op.drop_index(op.f('idx_user_organization_active'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_user_organization_active'), 'users', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('idx_user_name_search'), 'users', ['first_name', 'last_name'], unique=False)
    op.create_index(op.f('idx_timer_user_running'), 'timers', ['user_id', 'is_running'], unique=False)
    op.create_index(op.f('idx_timer_task'), 'timers', ['task_id'], unique=False)
    op.create_index(op.f('idx_timer_start_time'), 'timers', ['start_time'], unique=False)
    op.create_index(op.f('idx_timer_project_running'), 'timers', ['project_id', 'is_running'], unique=False)
    op.drop_column('timers', 'paused_duration')
    op.drop_column('timers', 'paused_at')
    op.drop_column('timers', 'is_paused')
    op.create_index(op.f('idx_time_entry_user_date'), 'time_entries', ['user_id', 'start_time'], unique=False)
    op.create_index(op.f('idx_time_entry_task'), 'time_entries', ['task_id'], unique=False)
    op.create_index(op.f('idx_time_entry_project_date'), 'time_entries', ['project_id', 'start_time'], unique=False)
    op.create_index(op.f('idx_time_entry_date_range'), 'time_entries', ['start_time', 'end_time'], unique=False)
    op.create_index(op.f('idx_time_entry_billable'), 'time_entries', ['is_billable'], unique=False)
    op.create_index(op.f('idx_task_project_status'), 'tasks', ['project_id', 'status'], unique=False)
    op.create_index(op.f('idx_task_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('idx_task_billable'), 'tasks', ['is_billable'], unique=False)
    op.create_index(op.f('idx_task_assignee_status'), 'tasks', ['assignee_id', 'status'], unique=False)
    op.create_unique_constraint(op.f('uq_project_name_org'), 'projects', ['name', 'organization_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_project_org_active'), 'projects', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('idx_project_name_org'), 'projects', ['name', 'organization_id'], unique=False)
    op.create_index(op.f('idx_project_client'), 'projects', ['client_id'], unique=False)
    op.create_index(op.f('idx_org_slug_active'), 'organizations', ['slug', 'is_active'], unique=False)
    op.create_index(op.f('idx_org_name'), 'organizations', ['name'], unique=False)
    op.add_column('clients', sa.Column('payment_terms', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('address_line1', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('hourly_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('address_line2', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('tax_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('company_registration', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uq_client_name_org'), 'clients', ['name', 'organization_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=False)
    op.create_index(op.f('idx_client_org_active'), 'clients', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('idx_client_name_org'), 'clients', ['name', 'organization_id'], unique=False)
    op.create_index(op.f('idx_client_email'), 'clients', ['email'], unique=False)
    op.alter_column('clients', 'website',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
    op.alter_column('clients', 'email',
               existing_type=sa.String(length=254),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('clients', 'address')
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('tags_organization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tags_pkey')),
    sa.UniqueConstraint('name', 'organization_id', name=op.f('uq_tag_name_org'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('idx_tag_org_active'), 'tags', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('idx_tag_name_org'), 'tags', ['name', 'organization_id'], unique=False)
    op.create_table('project_assignments',
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_assignments_project_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('project_assignments_user_id_fkey'))
    )
    op.create_table('task_tags',
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('task_tags_tag_id_fkey')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('task_tags_task_id_fkey')),
    sa.PrimaryKeyConstraint('task_id', 'tag_id', name=op.f('task_tags_pkey'))
    )
    op.create_table('project_tags',
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_tags_project_id_fkey')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('project_tags_tag_id_fkey')),
    sa.PrimaryKeyConstraint('project_id', 'tag_id', name=op.f('project_tags_pkey'))
    )
    op.create_table('time_entry_tags',
    sa.Column('time_entry_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('time_entry_tags_tag_id_fkey')),
    sa.ForeignKeyConstraint(['time_entry_id'], ['time_entries.id'], name=op.f('time_entry_tags_time_entry_id_fkey')),
    sa.PrimaryKeyConstraint('time_entry_id', 'tag_id', name=op.f('time_entry_tags_pkey'))
    )
    op.drop_index(op.f('ix_timesheets_id'), table_name='timesheets')
    op.drop_table('timesheets')
    # ### end Alembic commands ###